apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: "{{ .Values.name }}"
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.port }}
        # - env:
        #     # - name: API_KEY
        #     #   value: d35af1556ed30e0098eaf8c9bf829057b7cca565
        #     - name: COLLECTION_NAME
        #       value: collection
        #     - name: DB_NAME
        #       value: rezilion
        #     - name: HOST
        #       value: mongodb.default.svc.cluster.local
        #     # - name: ME_CONFIG_MONGODB_URL
        #     #   value: mongodb://citizix:S3cret@127.0.0.1:27017/
        #     - name: MONGO_INITDB_ROOT_PASSWORD
        #       value: S3cret
        #     - name: MONGO_INITDB_ROOT_USERNAME
        #       value: citizix
        #     - name: PORT
        #       value: "27017"
        #     - name: STORE_LIST
        #       value: '[305, 29, 148]'
status: {}
