apiVersion: v1
kind: Namespace
metadata:
  name: rezilion
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hermes
  namespace: rezilion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hermes
  namespace: rezilion
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  - pods/exec
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hermes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hermes
subjects:
- kind: ServiceAccount
  name: hermes
  namespace: rezilion
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: hermes
  name: rezilion-hermes
  namespace: rezilion
spec:
  selector:
    matchLabels:
      name: rezilion-hermes
  template:
    metadata:
      labels:
        name: rezilion-hermes
    spec:
      containers:
      - env:
        - name: HOST_ROOT
          value: /tmp/host_root
        - name: HERMES_HOST_SCOPE
          value: all
        - name: HERMES_CONTAINERS_SCOPE
          value: all
        - name: HERMES_IDENTIFIER
          value: hostname
        - name: HERMES_LIFE_TIME
          value: 8h
        - name: HERMES_SAMPLE_INTERVAL
          value: 0s
        - name: HERMES_ACCEPTED_EULA
          value: 'yes'
        - name: HERMES_UPLOAD_INTERVAL
          value: 1h
        - name: HERMES_TEMP_DISK_STORAGE_PATH
          value: /home
        - name: HERMES_CONTAINERS_ONLY
          value: 'yes'
        - name: HERMES_EXECUTION_WITHOUT_CGROUPS
          value: periodic-run
        - name: COMMON_API_KEY
          value: "Qloeq2OjzC7mD0EmpNblH8vzcUOMT7433aJ2rLuw"
        - name: HERMES_DESTINATION
          value: https://api.rezilion.com
        - name: HERMES_ENVIRONMENT
          value: default
        image: rezilion/instrument:a7cebb3d
        imagePullPolicy: Always
        name: rezilion-hermes
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps -ef | grep maia | grep -v grep
        resources:
          limits:
            cpu: 200m
            memory: 1024M
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: hermes-claim1
        - mountPath: /tmp/host_root
          name: hermes-claim2
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
      - name: rezilioncreds
      restartPolicy: Always
      serviceAccountName: hermes
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: hermes-claim1
      - hostPath:
          path: /
        name: hermes-claim2
---
...
